---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.33.33"}]
provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5 

suites:
  - name: default
    run_list: recipe[hackday::default]
    attributes:
